CREATE OR REPLACE TRIGGER SCH_CN.GL_GCLIENTES BEFORE
INSERT
  ON SCH_CN.GL_TCLIENTES FOR EACH ROW BEGIN
    SELECT
   SCH_CN.GL_SCLIENTES.NEXTVAL INTO :NEW.CLI_ID
    FROM
      DUAL;
END;

CREATE TRIGGER SCH_CN.GL_GBODEGA BEFORE
INSERT
  ON SCH_CN.GL_TBODEGA FOR EACH ROW BEGIN
    SELECT
   SCH_CN.GL_SBODEGA.NEXTVAL INTO :NEW.BOD_ID
    FROM
      DUAL;
END;

CREATE OR REPLACE TRIGGER SCH_CN.GL_GENVIO 
BEFORE INSERT ON SCH_CN.GL_TENVIO 
  FOR EACH ROW 
   BEGIN
    SELECT
      SCH_CN.GL_SENVIO.NEXTVAL 
	   INTO :NEW.ENV_ID
       FROM
       DUAL;
END;



ALTER TABLE SCH_CN.GL_TENVIO
  ADD CONSTRAINT pk_GENVIO_dt PRIMARY KEY( ENV_ID );
  

CREATE TRIGGER SCH_CN.GL_GDETALLEENVIO BEFORE
INSERT
  ON SCH_CN.GL_TDETALLEENVIO FOR EACH ROW BEGIN
    SELECT
   SCH_CN.GL_SDETALLEENVIO.NEXTVAL INTO :NEW.ENVD_ID
    FROM
      DUAL;
END;


CREATE TRIGGER SCH_CN.GL_GDETALLEENVIOTEMP BEFORE
INSERT
  ON SCH_CN.GL_TDETALLEENVIOTEMP FOR EACH ROW BEGIN
    SELECT
   SCH_CN.GL_SDETALLEENVIOTEMP.NEXTVAL INTO :NEW.ENVDT_IDP
    FROM
      DUAL;
END;



CREATE TRIGGER SCH_CN.GL_GZONAS BEFORE
INSERT
  ON SCH_CN.GL_TZONAS FOR EACH ROW BEGIN
    SELECT
   SCH_CN.GL_SZONAS.NEXTVAL INTO :NEW.ZON_ID
    FROM
      DUAL;
END;

CREATE OR REPLACE TRIGGER SCH_CN.GL_GUSUARIOS 
BEFORE INSERT ON SCH_CN.GL_TUSUARIOS
 FOR EACH ROW 
   BEGIN
    SELECT SCH_CN.GL_SUSUARIOS.NEXTVAL
 	INTO :NEW.USU_ID 
	FROM DUAL;
END;

ALTER TABLE SCH_CN.GL_TUSUARIOS
  ADD CONSTRAINT pk_GUSUARIOS_dt PRIMARY KEY( USU_ID );

CREATE TRIGGER SCH_CN.GL_GTIPOPRODUCTO BEFORE
INSERT
  ON SCH_CN.GL_TTIPOPRODUCTO FOR EACH ROW BEGIN
    SELECT
   SCH_CN.GL_STIPOPRODUCTO.NEXTVAL INTO :NEW.TIPOPR_ID
    FROM
      DUAL;
END;

CREATE TRIGGER SCH_CN.GL_GTIPODOCUMENTO BEFORE
INSERT
  ON SCH_CN.GL_TTIPODOCUMENTO FOR EACH ROW BEGIN
    SELECT
   SCH_CN.GL_STIPODOCUMENTO.NEXTVAL INTO :NEW.TDOC_ID
    FROM
      DUAL;
END;

CREATE TRIGGER SCH_CN.GL_GTIPOBODEGA BEFORE
INSERT
  ON SCH_CN.GL_TTIPOBODEGA FOR EACH ROW BEGIN
    SELECT
   SCH_CN.GL_STIPOBODEGA.NEXTVAL INTO :NEW.TIPOB_ID
    FROM
      DUAL;
END;

CREATE TRIGGER SCH_CN.GL_GROLES BEFORE
INSERT
  ON SCH_CN.GL_TROLES FOR EACH ROW BEGIN
    SELECT
   SCH_CN.GL_SROLES.NEXTVAL INTO :NEW.ROL_ID
    FROM
      DUAL;
END;

CREATE TRIGGER SCH_CN.GL_GPRODUCTOS BEFORE
INSERT
  ON SCH_CN.GL_TPRODUCTOS FOR EACH ROW BEGIN
    SELECT
   SCH_CN.GL_SPRODUCTOS.NEXTVAL INTO :NEW.PRO_ID
    FROM
      DUAL;
END;