CREATE SEQUENCE SCH_CN.GL_SCLIENTES
START WITH
    1 INCREMENT BY 1;
	
	CREATE SEQUENCE SCH_CN.GL_SBODEGA
START WITH
    1 INCREMENT BY 1;
	
	CREATE SEQUENCE SCH_CN.GL_SENVIO
START WITH
    1 INCREMENT BY 1;
	
	CREATE SEQUENCE SCH_CN.GL_SDETALLEENVIO
START WITH
    1 INCREMENT BY 1;
	
	CREATE SEQUENCE SCH_CN.GL_SDETALLEENVIOTEMP
START WITH
    1 INCREMENT BY 1;
	
	CREATE SEQUENCE SCH_CN.GL_SZONAS
START WITH
    1 INCREMENT BY 1;
	
	CREATE SEQUENCE SCH_CN.GL_SUSUARIOS
START WITH
    1 INCREMENT BY 1;
	
	CREATE SEQUENCE SCH_CN.GL_STIPOPRODUCTO
START WITH
    1 INCREMENT BY 1;
	
	CREATE SEQUENCE SCH_CN.GL_STIPODOCUMENTO
START WITH
    1 INCREMENT BY 1;
	
		CREATE SEQUENCE SCH_CN.GL_STIPOBODEGA
START WITH
    1 INCREMENT BY 1;
	
		CREATE SEQUENCE SCH_CN.GL_SROLES
START WITH
    1 INCREMENT BY 1;
	
		CREATE SEQUENCE SCH_CN.GL_SPRODUCTOS
START WITH
    1 INCREMENT BY 1;